apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: ZDk1ZmQ0ZDMzMTRiMWY4Yg==
  AWS_SECRET_ACCESS_KEY: YzA1ZWViNDFkMjUxODdmNDM3Y2ZmZmVmNTU0MGQ0ODUyMzAwOTZkYzdiM2NkNGJkMjkzZDkwY2E1ZTYwMTg1ZA==
  MINIO_ACCESS_KEY: ZDk1ZmQ0ZDMzMTRiMWY4Yg==
  MINIO_SECRET_KEY: YzA1ZWViNDFkMjUxODdmNDM3Y2ZmZmVmNTU0MGQ0ODUyMzAwOTZkYzdiM2NkNGJkMjkzZDkwY2E1ZTYwMTg1ZA==
  POSTGRES_DB: b3V0bGluZS10ZXN0
  POSTGRES_PASSWORD: cGFzcw==
  POSTGRES_USER: dXNlcg==
  SECRET_KEY: NjEzZWMwMzMyZDEzMDU5ZWFkYWQ0MGIyZDgzOTJlNGRmMTQ4ZjNiMDhmY2IzYTNhOWI2Y2Q2MzQ4YTRlMDgwYg==
  SLACK_APP_ID: QTA3UjI3WDg0VEI=
  SLACK_KEY: MzE2NjAyNjc1NDI5MS43ODUyMjY5Mjc2OTI5
  SLACK_SECRET: ODVhMTA3ZDExMzI2ODk3NDQyZDkzMzFmYjQyNWE5MGY=
  SLACK_VERIFICATION_TOKEN: bk1HaG9oaUtpcjBURERRT05DSjgyelB0
  UTILS_SECRET: NDY0NTYzMzY3MzcxNzE3MmUyMjU5Yjg2N2JkMzgyYWI2NzM1MTRmNGU3ODM4YmQxOGRkNzBlY2NhYTBkZTNjNQ==
kind: Secret
metadata:
  name: outline
  namespace: outline
type: Opaque
